version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cloudpulse-postgres
    environment:
      POSTGRES_USER: cloudpulse
      POSTGRES_PASSWORD: cloudpulse
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: